# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KituraRegistrationClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift'#, '~> 4.1.0'
  pod 'RxCocoa'
  pod 'Action'
  pod 'SwiftyJSON', '4.0.0'
  pod 'Then'
  pod 'SnapKit'
  pod 'RxGesture'
  #pod 'RxSwiftUtilities'
  target 'KituraRegistrationClientTests' do
    inherit! :search_paths
    pod 'RxTest'#,'~> 4.1.0'
    pod 'RxBlocking'#,'~> 4.1.0'
    pod 'RxSwift'#, '~> 4.1.0'
    pod 'RxCocoa'
  end
end
